name = "PETSC"
uuid = "1194c000-87c4-4102-b4a0-a6217ec4849e"
authors = ["Francesc Verdugo <f.verdugo.rojano@vu.nl> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
